### PR TITLE
feat: add possiblity for the flow steps to be arrays of steps

### PR DESCRIPTION
**Pull request by stambata**
Add possiblity for the flow items to be an array of objects describing a sequence of steps.

* This will improve the readability as it won't be necessary to concatenate arrays when writing tests with dynamic steps anymore.
* This will make the code reuse easier by abstracting sequences of steps.

### CODE REVIEW

**Comment by kalinkrustev** [comment]
Looks good, waiting feedback from @venetahristova

**Comment by stambata** [comment]
I changed code so that the steps can be built even recursively.

**Comment by venetahristova** [comment]
We can do this with sub test functionality as well, but if we need this to be a main step it is ok.

**Comment by venetahristova** [comment]
Should we merge this into master?

**Comment by kalinkrustev** [comment]
I have created cubalibre branch from this one.

**Pull request closed without merging**
